apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api-server-dapr
  labels:
    app: simple-api-server-dapr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-api-server-dapr
  template:
    metadata:
      labels:
        app: simple-api-server-dapr
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "simpleapi"
        dapr.io/app-port: "3000"
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: server
          image: "pcreuwcore.azurecr.io/simpleapi:latest"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "50Mi"
              cpu: "300m"
            limits:
              memory: "50Mi"
              cpu: "300m"
          lifecycle: 
            preStop:
              httpGet:
                path: /api/podTerminate
                port: 3000
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/podReady
              port: http
          readinessProbe:
            httpGet:
              path: /api/podReady
              port: http